# Generated by Django 5.2.13 on 2026-05-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_backfill_oauth_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_about_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Free-form Markdown bio rendered on the public profile.",
                max_length=5000,
                verbose_name="Profile About (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_headline",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short one-line tagline shown at the top of the profile page.",
                max_length=200,
                verbose_name="Profile Headline",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_links_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown list of links rendered on the public profile.",
                max_length=5000,
                verbose_name="Profile Links (Markdown)",
            ),
        ),
    ]
